library("rstan")
library("psych")
library("shinystan")
library("ggplot2")
library("TAM")
library("reshape2")
library("loo")
library("MASS")


options(scipen = 999)
options(max.print = 100000)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

source("src/modules/createScoresTable.R")
source("src/modules/fitModel.R")
source("src/modules/generateData.R")
source("src/modules/generateItems.R")
source("src/modules/generatePersons.R")
source("src/modules/generateResponses.R")
source("src/modules/getModelDiscrepancies.R")
source("src/modules/hdi.R")
source("src/modules/checkCancellation.R")
source("src/modules/checkMatrix.R")
source("src/modules/inverseLogit.R")
source("src/modules/pairwiseItemOddsRatios.R")
source("src/modules/parametricPersonFit.R")
source("src/modules/personBiserialCorrelations.R")
source("src/modules/scoresDistribution.R")
source("src/modules/scoresDistributionFit.R")
source("src/modules/summarizeSamples.R")
source("src/modules/testData.R")
source("src/modules/visualizeItems.R")
source("src/modules/visualizePersons.R")
source("src/modules/visualizeResponses.R")
source("src/modules/writeResult.R")
source("src/modules/zeros.R")
